[package]
name = "maze"
version = "0.1.0"
entrypoint = "maze.typ"
authors = ["Piotr Beling"]
license = "MIT"
description = "Maze generator for Typst."
repository = "https://github.com/beling/typst-maze"

[dependencies]
suiji = "0.5.1"

[keywords]
keywords = ["maze", "labyrinth", "typst", "graphics", "procedural", "random"]